import { NodePresentationConfig } from '../../widgets/core/types/node-presentation-config';
import {
  aboutWidget,
  additionalTypeWidget,
  addressWidget,
  birthDateWidget,
  birthPlaceWidget,
  contentLocationWidget,
  creatorWidget,
  datasetWidget,
  dateCreatedWidget,
  deathDateWidget,
  deathPlaceWidget,
  descriptionHeaderWidget,
  fallbackWidget,
  genreWidget,
  geoWidget,
  hasOccupationWidget,
  isBasedOnWidget,
  isMockDataWidget,
  isPartOfLicenseWidget,
  isPartOfPublisherWidget,
  licenseWidget,
  materialWidget,
  mediaWidget,
  nameWidget,
  publisherWidget,
  referringNodesWidget,
  typeWidget,
} from './widgets/widgets';

export const DETAILS_PRESENTATION_CONFIG: NodePresentationConfig = {
  widgets: [
    nameWidget,
    descriptionHeaderWidget,
    mediaWidget,
    typeWidget,
    additionalTypeWidget,
    isMockDataWidget,
    licenseWidget,
    publisherWidget,
    hasOccupationWidget,
    genreWidget,
    aboutWidget,
    contentLocationWidget,
    birthPlaceWidget,
    deathPlaceWidget,
    materialWidget,
    creatorWidget,
    dateCreatedWidget,
    birthDateWidget,
    deathDateWidget,
    geoWidget,
    addressWidget,
    fallbackWidget,
    isPartOfLicenseWidget,
    datasetWidget,
    isPartOfPublisherWidget,
    isBasedOnWidget,
    referringNodesWidget,
    // separatorWidget,
  ],
};
