import { NodePresentationConfig } from '../../widgets/core/types/node-presentation-config';
import {
  aboutWidget,
  additionalTypeWidget,
  addressWidget,
  birthDateWidget,
  birthPlaceWidget,
  creatorWidget,
  datasetWidget,
  dateCreatedWidget,
  deathDateWidget,
  deathPlaceWidget,
  descriptionHeaderWidget,
  fallbackWidget,
  genreWidget,
  geoWidget,
  hasOccupationWidget,
  idAsLinkWidget,
  isBasedOnWidget,
  licenseWidget,
  locationWidget,
  materialWidget,
  mediaWidget,
  nameWidget,
  publisherWidget,
  referringNodesWidget,
  separatorWidget,
  sizeWidget,
  textWidget,
} from './widgets/widgets';

export const DETAILS_PRESENTATION_CONFIG: NodePresentationConfig = {
  widgets: [
    {
      id: 'hideProperties',
      properties: [
        'label',
        'sdDatePublished',
        'hasMedia',
        'identifier',
        'isPartOf',
        'iiifManifest',
        'associatedMedia',
        'type',
      ],
      componentId: 'text-widget',
      hidden: true,
    },
    nameWidget,
    descriptionHeaderWidget,
    textWidget,
    mediaWidget,
    additionalTypeWidget,
    licenseWidget,
    publisherWidget,
    hasOccupationWidget,
    genreWidget,
    aboutWidget,
    locationWidget,
    birthPlaceWidget,
    deathPlaceWidget,
    materialWidget,
    creatorWidget,
    dateCreatedWidget,
    birthDateWidget,
    deathDateWidget,
    geoWidget,
    addressWidget,
    fallbackWidget,
    isBasedOnWidget,
    referringNodesWidget,
    sizeWidget,
    separatorWidget,
    datasetWidget,
    idAsLinkWidget,
  ],
};
