fragment DatasetReferenceFields on DatasetReference {
  id
  label {
    value
    language
  }
}

fragment PersonReferenceFields on PersonReference {
  id
  label {
    value
    language
  }
}

fragment PlaceReferenceFields on PlaceReference {
  id
  label {
    value
    language
  }
}

fragment TermReferenceFields on TermReference {
  id
  label {
    value
    language
  }
}

fragment PublisherReferenceFields on PublisherReference {
  id
  label {
    value
    language
  }
}

fragment OccupationReferenceFields on OccupationReference {
  id
  label {
    value
    language
  }
}

fragment MediaObjectFields on MediaObject {
  id
  thumbnailUrl
  contentUrl
  license
  copyrightNotice {
    value
    language
  }
  encodingFormat
}

fragment CreativeWorkFields on CreativeWork {
  id
  type
  name {
    value
    language
  }
  sdDatePublished
  isPartOf {
    ...DatasetReferenceFields
  }
  creator {
    ...PersonReferenceFields
  }
  creatorName {
    value
    language
  }
  identifier
  additionalType {
    ...TermReferenceFields
  }
  description {
    value
    language
  }
  abstract {
    value
    language
  }
  text {
    value
    language
  }
  size {
    value
    language
  }
  contentLocation {
    ...PlaceReferenceFields
  }
  temporalCoverage
  locationCreated {
    ...PlaceReferenceFields
  }
  dateCreated
  about {
    ...TermReferenceFields
  }
  material {
    ...TermReferenceFields
  }
  genre {
    ...TermReferenceFields
  }
  associatedMedia {
    ...MediaObjectFields
  }
  iiifManifest
  hasMedia
}

fragment CreativeWorkFacetFields on CreativeWorkFacets {
  type {
    value
    count
    label {
      value
      language
    }
  }
  dataset {
    value
    count
    label {
      value
      language
    }
  }
  isPartOf {
    value
    count
    label {
      value
      language
    }
  }
  creator {
    value
    count
    label {
      value
      language
    }
  }
  additionalType {
    value
    count
    label {
      value
      language
    }
  }
  contentLocation {
    value
    count
    label {
      value
      language
    }
  }
  temporalCoverage {
    value
    count
    label {
      value
      language
    }
  }
  locationCreated {
    value
    count
    label {
      value
      language
    }
  }
  about {
    value
    count
    label {
      value
      language
    }
  }
  material {
    value
    count
    label {
      value
      language
    }
  }
  genre {
    value
    count
    label {
      value
      language
    }
  }
  license {
    value
    count
    label {
      value
      language
    }
  }
  hasMedia {
    value
    count
  }
}

fragment TermFields on Term {
  id
  label {
    value
    language
  }
  sameAs
}

fragment DatasetFields on Dataset {
  id
  label {
    value
    language
  }
  license
  publisher {
    ...PublisherReferenceFields
  }
}

fragment OccupationFields on Occupation {
  id
  label {
    value
    language
  }
}

fragment OrganizationFields on Organization {
  id
  label {
    value
    language
  }
  location {
    ...PlaceReferenceFields
  }
}

fragment PersonFields on Person {
  id
  label {
    value
    language
  }
  birthDate
  birthPlace {
    ...PlaceReferenceFields
  }
  deathDate
  deathPlace {
    ...PlaceReferenceFields
  }
  hasOccupation {
    ...OccupationReferenceFields
  }
}

fragment PlaceFields on Place {
  id
  label {
    value
    language
  }
  addressCountry
  addressLocality
  addressRegion
  postalCode
  streetAddress
  latitude
  longitude
}

fragment ReferringCreativeWorkFields on CreativeWork {
  id
  type
  name {
    value
    language
  }
  associatedMedia {
    thumbnailUrl
  }
}

fragment ReferringDatasetFields on Dataset {
  id
  label {
    value
    language
  }
}

fragment ReferringOccupationFields on Occupation {
  id
  label {
    value
    language
  }
}

fragment ReferringOrganizationFields on Organization {
  id
  label {
    value
    language
  }
}

fragment ReferringPersonFields on Person {
  id
  label {
    value
    language
  }
}

fragment ReferringPlaceFields on Place {
  id
  label {
    value
    language
  }
}

fragment ReferringTermFields on Term {
  id
  label {
    value
    language
  }
}
