import { NodePresentationConfig } from '../../widgets/core/types/node-presentation-config';
import { baseWidgets } from './widgets/base-widgets';
import {
  aboutWidget,
  addressWidget,
  birthDateWidget,
  birthPlaceWidget,
  contentLocationWidget,
  creatorWidget,
  dateCreatedWidget,
  deathDateWidget,
  deathPlaceWidget,
  descriptionHeaderWidget,
  fallbackWidget,
  genreWidget,
  geoWidget,
  hasOccupationWidget,
  isBasedOnWidget,
  isMockDataWidget,
  isPartOfLicenseWidget,
  isPartOfPublisherWidget,
  licenseWidget,
  materialWidget,
  mediaWidget,
  publisherWidget,
  referringNodesWidget,
} from './widgets/widgets.config';

export const DETAILS_PRESENTATION_CONFIG: NodePresentationConfig = {
  widgets: [
    ...baseWidgets,
    descriptionHeaderWidget,
    isMockDataWidget,
    licenseWidget,
    publisherWidget,
    hasOccupationWidget,
    genreWidget,
    aboutWidget,
    contentLocationWidget,
    birthPlaceWidget,
    deathPlaceWidget,
    mediaWidget,
    materialWidget,
    creatorWidget,
    dateCreatedWidget,
    birthDateWidget,
    deathDateWidget,
    geoWidget,
    addressWidget,
    isPartOfLicenseWidget,
    isPartOfPublisherWidget,
    isBasedOnWidget,
    referringNodesWidget,
  ],
  display: [
    {
      widgetIds: ['name', 'description-header'],
    },
    {
      widgetIds: [
        'media',
        'type',
        'additional-type',
        '*',
        'is-part-of-license',
      ],
    },
    {
      widgetIds: ['dataset', 'is-part-of-publisher', 'is-based-on'],
    },
    {
      widgetIds: ['referring-nodes'],
    },
  ],
  fallbackWidget: fallbackWidget,
  showArrowIndicator: true,
};
