fragment DatasetReferenceFields on DatasetReference {
  id
  name {
    value
    language
  }
  publisher {
    ...PublisherReferenceFields
  }
  license
  description {
    value
    language
  }
  landingPage
}

fragment PersonReferenceFields on PersonReference {
  id
  name {
    value
    language
  }
}

fragment PlaceReferenceFields on PlaceReference {
  id
  latitude
  longitude
  addressCountry
  addressLocality
  addressRegion
  authority
  fetchedAt
  name {
    language
    value
  }
  postalCode
  streetAddress
}

fragment TermReferenceFields on TermReference {
  id
  name {
    value
    language
  }
}

fragment PublisherReferenceFields on PublisherReference {
  id
  name {
    value
    language
  }
}

fragment OccupationReferenceFields on OccupationReference {
  id
  name {
    value
    language
  }
}
